name: Actions Test

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  lima-on-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: lima-vm/lima-actions/setup@v1
      - name: Start default VM
        run: limactl start --name=default --tty=false
        timeout-minutes: 10
      - name: Verify VM is running
        run: limactl list
      - name: Run uname in VM
        run: limactl shell default uname -a
      - name: Run cat /etc/os-release in VM
        run: limactl shell default cat /etc/os-release
